README.md

**Add proposal folders to keep raisd proposals from community and also update the README to reflect the change**

Add proposal folders to keep raisd proposals from community

---

MAINTAINERS.md

[@mmpei](https://github.com/mmpei) is from China top internet company Netease and working on the container related domain.
He's very actively involved in the harbor community and did very important contributions in the last release(V1.7). He implemented the [database logger](https://github.com/mmpei) for the running job in a very tight timeline. He is willing and committed to doing more contributions in the next release. He'll work on the webhook feature as well as the replication enhancement feature.
I think [@mmpei](https://github.com/mmpei) is a qualified maintainer of Harbor community. So I'd like to launch this nomination. Please review and vote.

Nominate @nmpei as Harbor maintainer

---

MEETING_SCHEDULE.md
conf-calls/2018-12-26/minutes.md

add meeting minutes for 18-12-06 and update the meeting schedule

add meeting minutes for 18-12-06 and update the meeting schedule

---

conf-calls/2018-11-07/minutes.md

Signed-off-by: wang yan <wangyan@vmware.com>

Add community minutes of 2018-11-07

---

conf-calls/2018-11-28/minutes.md

Signed-off-by: wang yan <wangyan@vmware.com>

Add minutes of 2018-11-28

---

README.md
workgroups/wg-replication/sync-meetings/2018-12-21/minutes.md
workgroups/wg-replication/sync-meetings/2018-12-25/minutes.md
workgroups/wg-replication/sync-meetings/2019-01-04/minutes.md
workgroups/wg-replication/sync-meetings/2019-01-08/minutes.md
workgroups/wg-replication/sync-meetings/2019-01-16/minutes.md
workgroups/wg-replication/sync-meetings/2019-01-22/minutes.md
workgroups/wg-replication/sync-meetings/2019-01-30/minutes.md

add meeting minutes for the latest sync 2019/01/30

---

MAINTAINERS.md

I am no longer part of VMware's Harbor team. I will be working on this upstream project independent of any particular corporate affiliation and will also be voting independently.
@nlowe can you please approve so that this PR can be merged? Thanks!
/cc @caniszczyk @goharbor/all-maintainers 
Signed-off-by: clouderati <35942204+clouderati@users.noreply.github.com>

Updating maintainer affiliation

---

MAINTAINERS.md

fixing typo in james github link to clouderati

updating James github link

---

workgroups/wg-replication/README.md
workgroups/wg-replication/sync-meetings/2019-02-20/minutes.md

Add meeting minutes for replication wg @2019/02/20

add meeting minutes for replication wg @2019/02/20

---

proposals/CLI-Password.md

Signed-off-by: Daniel Jiang <jiangd@vmware.com>

Add proposal for CLI password

---

workgroups/wg-replication/README.md
workgroups/wg-replication/sync-meetings/2019-03-28/minutes.md
workgroups/wg-replication/sync-meetings/2019-04-03/minutes.md
workgroups/wg-replication/sync-meetings/2019-04-09/minutes.md

Signed-off-by: Wenkai Yin <yinw@vmware.com>

Meeting minutes for replication work group

---

MAINTAINERS.md

I'd like to nominate [hainingzhang](https://github.com/hainingzhang) who's the founder of Harbor project as a new core maintainer with high respects as he's still willing to supervise, promote and do contributions to the Harbor community!

Nominate Henry Zhang who's the founder of Harbor project as core maintainer

---

MAINTAINERS.md

I'm so glad to nominate [Michael Michael](https://github.com/michmike) to be core maintainer of the Harbor community based on the facts that MM will fill the gap of the product/project management with his rich related experiences as well as:
* MM is defining the overall roadmap of Harbor and will do contributions to the release plans
* check [Harbor Project Board](https://github.com/orgs/goharbor/projects/1)
* MM regularly hosts the community meeting of US time zone
* MM will take the responsibilities of being Harbor evangelist of US/Europe
* MM will be the primary contact point to the CNCF to collaborate relationship between Harbor and CNCF
* MM has submitted many commits to refine the docs/process/plans etc. of Harbor community.
IMO, MM is qualified as a Harbor core maintainer and I …

nominate Michael Michael as core maintainer of Harbor

---

workgroups/wg-scanning/README.md

Per discussion with @steven-zou , this is a PR purely for a README to create the scanning workgroup.

Adds README.md for new scanning workgroup

---

proposals/CVE_Whitelist.md

Signed-off-by: Daniel Jiang <jiangd@vmware.com>

Add proposal for supporting vulnerability whitelist

---

workgroups/wg-p2p/README.md

Signed-off-by: cd1989 <chende@caicloud.io>

Create p2p working group

---

workgroups/wg-operator/README.md

1. Introduce of this group.
2. Members list.
Signed-off-by: 疯魔慕薇 <kfanjian@gmail.com>

Operator Workgroup

---

MEETING_SCHEDULE.md

Signed-off-by: Ziming Zhang <zziming@vmware.com>

add confcall record 20190814

---

MEETING_SCHEDULE.md

Signed-off-by: xaleeks <xalex@vmware.com>

change url of community meeting recording

---

MAINTAINERS.md
conf-calls/2018-10-24/minutes.md
workgroups/wg-p2p/README.md
workgroups/wg-replication/README.md

Signed-off-by: De Chen <xxyydream@gmail.com>
Update Chen De's affiliation

Update Chen De's affiliation

---

presentations/introduction/workshop.md

The initial workshop doc with rough instructions for installation and tasks to complete
Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>

Added initial workshop doc

---

proposals/new/immutable_tags.md

Signed-off-by: stonezdj <stonezdj@gmail.com>

Add immutable tags proposal

---

MAINTAINERS.md

Signed-off-by: dechen <dechen@tencent.com>

Update cd1989's affiliation

---

.gitignore
MAINTAINERS.md

hi @goharbor/maintainers 
I'm so glad to nominate Alex Xu(@xaleeks) as our new maintainer. Alex will continue to focus on the product management of the Harbor project(s) and promote the rapid development of the harbor project and community for the next greater achievements. Alex has been:
* maintaining the overall roadmap of Harbor and will do contributions to the release plans
* check [Harbor Project Board](https://github.com/orgs/goharbor/projects/1)
* check [Roadmap](https://github.com/goharbor/harbor/blob/master/ROADMAP.md)
* regularly hosting the community meetings
* triaging kinds of requirements from the community and deeply diving valuable ones
* supervising feature development via PRDs
* speaking Harbor in kinds of conferences(e.g: KubeCon) and webinars
* collaborating with …

chore(nominations):nominate alex xu as maintainer

---

proposals/new/webhook-token-authentication.md

Signed-off-by: Daniel Jiang <jiangd@vmware.com>

Add proposal for webhook token authn in CLI

---

GOVERNANCE.md
MAINTAINERS.md

Hi @goharbor/maintainers,
Nominating Tianon Gravi from InfoSiftr to be the maintainer of the Harbor community.

chore[community]:nominate  Tianon Gravi to be Harbor maintainers

---

MAINTAINERS.md

Add Roger as PM instead of Alex
Add Alex to emeratus maintainers

Updates in MAINTAINERS file

---

proposals/new/audit_log.md

Add options to forward audit_log to log stream
Add option to rotate audit log table

Add proposal to rotate audit log

---

proposals/cache-layer.md

Signed-off-by: chlins <chenyuzh@vmware.com>

feat: introduce proposal for cache layer

---

MAINTAINERS.md

I had hoped to continue contributing, but I unfortunately do not have the bandwidth anymore [in my new role at Docker, Inc](https://www.docker.com/blog/docker-acquires-long-time-partner-infosiftr/), and I felt it was doing the project a disservice to keep me listed here. :two_hearts:
Collaborating here has been a privilege, and I'm definitely still open to helping out where I can, especially if there are conversations where my knowledge might be useful! :+1:
(Sorry @OrlinVasilev -- I know we've been trying to connect for weeks :see_no_evil: :heart:  Hopefully you can understand!)

Move Tianon to Emeritus Maintainers

---

CODEOWNERS

 Add CODEOWNERS file to auto assign folks from SIG community

---

README.md

Add slack links in readme and link to community page

---

.github/auto-assignees.yml
.github/workflows/auto_assign_prs.yml

Add auto-assignees for PRs
